### ISSUE TITLE
Share process for creating the US cities and states list?

### ISSUE THREAD

**Issue by aqsmith08** [grammakov/us_cities_and_states#1]
Hi,

This list of US cities and states is helpful. Would you share your data source and the code you used to create this list? It'd be helpful. Thanks!

**Comment by grammakov** [comment]
Hey Aaron,
Thanks for stopping by. Here is the link to the file I've used. 
I didn't use code to make my list though, I did it manually.

https://www.dropbox.com/s/98fxvakllgoyh3e/List-of-Cities-States-and-Counties.xlsx?dl=0

**Comment by aqsmith08** [comment]
Wow. Even more impressive. :) Can I ask what site you used as your data source? Census.gov for example or was it something else? Thanks again.

**Comment by grammakov** [comment]
Sorry man, I found this excel file on an old fileshare hosting. No clue on where its coming from!

**Comment by aqsmith08** [comment]
Ah, makes sense. Appreciate the honesty and appreciate you posting it. I'm closing out this issue.
