### ISSUE TITLE
what is in the fourth field?

### ISSUE THREAD

**Issue by garfieldnate** [grammakov/us_cities_and_states#5]
This database is awesome!

What is in the fourth field (`Internal Revenue Service` below)?

```
City|State short|State full|County
Holtsville|NY|New York|SUFFOLK|Internal Revenue Service
```

**Comment by grammakov** [comment]
This is an attempt to have the ability to bind certain aliases to states/cities. E.g. Manhattan will take you to NY and so on.

**Comment by garfieldnate** [comment]
Makes sense, thanks.
